### ISSUE TITLE
origination_uuid not work

### ISSUE THREAD

**Issue by transtone** [xlab1/go-fs-secretary-prototype#1]
I test the secretary call, but it can't bridge two sessions. 
when use ' api originate {origination_uuid=xxx} ' ,it not use the uuid, but automatically create a new one.

**Comment by ssinyagin** [comment]
I don't know, it worked for me :)
what exactly are you running? Is it a clone of my code, or something different?

**Comment by transtone** [comment]
I tested in freeswitch-1.5.x git version and freeswitch-1.4.15. I edit nothing but '720@test01.voxserv.net' to 'sofia/gateway/serv1/12345678900' . And added "127.0.0.1:9090 async full" in dialplan/default.xml.

# 

sorry, It's my fault. I use the wrong cluecon ip address.

**Comment by transtone** [comment]
But why I can't bridge the two calls? when I press "3" on my mobile screen, caller hungup, and callee not hungup.

**Comment by ssinyagin** [comment]
I don't know anything about your environment and haven't seen any logs, so what kind of answer are you expecting?  :)

**Comment by transtone** [comment]
sorry。I has a new freeswitch system, copy the whole conf files to /etc/freeswitch . 
after set the dialplan socket and change the originate part to a gateway(the gateway work fine.)  in secretaryCallOut function, I can call my cell phone with a registed ip phone. 
when use ip phone dial my cellphone number:
1. IP phone heared the moh music.
2. cellphone ringing.
3. answer the cellphone, heared the "welcome to freeswitch" 
4. press a number (not 0), "welcome ...." gone. and IP phone hungup.

so, it can't make a call!

**Comment by ssinyagin** [comment]
can I have ssh access to the machine?

**Comment by transtone** [comment]
wait a second

**Comment by ssinyagin** [comment]
you can reach me in skype: ssinyagin

**Comment by ssinyagin** [comment]
I need to go out for half an hour, ping me in skype.

**Comment by transtone** [comment]
I register a skype account, but can't login.
when calling , got this message:
 [WARNING] switch_core_file.c:229 File has 2 channels, muxing to mono will occur.

zm3345@gmail.com

**Comment by ssinyagin** [comment]
let's switch to a private conversation, you can reach me at ssinyagin@gmail.com 
maybe Google Hangouts will work?

**Comment by ssinyagin** [comment]
I added my SSH public  key, you can change the password

**Comment by transtone** [comment]
I use the wang socket settings. It must be sync (not async)!
